apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-spec-sample 
spec:
  selector:
    matchLabels:
      app: app-demo-spec-sample
  template:
    metadata:
      labels:
        app: app-demo-spec-sample
    spec:
      containers:
        - image: okteto.dev/java-gradle-app-demo-spec-sample:1.0.0
          name: app-demo-spec-sample

---

apiVersion: v1
kind: Service
metadata:
  name: app-demo-spec-sample
spec:
  type: ClusterIP
  ports:
    - name: "app-demo-spec-sample"
      port: 8081
  selector:
    app: app-demo-spec-sample

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-demo-spec-sample
  annotations:
    dev.okteto.com/generate-host: app-demo-spec-sample
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: app-demo-spec-sample
                port:
                  number: 8081
            path: /
            pathType: ImplementationSpecific